import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { environment } from 'src/environments/environment';
import { Movie } from '../models/movie';
import { Theater } from '../models/theater';
import { User } from '../models/user';
import { MovieService } from '../movie.service';
import { UserService } from '../user.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  movies_list:any;
  user:any;
  constructor(private movieService:MovieService, private userService:UserService, private router: Router) { }

   movie2=
   {
     imageUrl:"../../assets/avengers.jpg",
     name:"Avengers",
     theaters:[
       {
        name:"INOX",
        address:"Marina Mall",
        shows:[
          {
            start_time:"10:00 AM",
            end_time:"12:30 PM",
            seats:[
            {
              number:"a1",
              status:"vacant"
            },
            {
              number:"a2",
              status:"occupied"
            },
            {
              number:"a3",
              status:"occupied"
            },
            {
              number:"a4",
              status:"vacant"
            },
            {
              number:"a5",
              status:"vacant"
            },
            {
              number:"b1",
              status:"vacant"
            },
            {
              number:"b2",
              status:"vacant"
            },
            {
              number:"b3",
              status:"vacant"
            },
            {
              number:"b4",
              status:"vacant"
            },
            {
              number:"b5",
              status:"vacant"
            },
            {
              number:"c1",
              status:"vacant"
            },
            {
              number:"c2",
              status:"vacant"
            },
            {
              number:"c3",
              status:"vacant"
            },
            {
              number:"c4",
              status:"vacant"
            },
            {
              number:"c5",
              status:"vacant"
            },
            {
              number:"d1",
              status:"occupied"
            },
            {
              number:"d2",
              status:"occupied"
            },
            {
              number:"d3",
              status:"occupied"
            },
            {
              number:"d4",
              status:"occupied"
            },
            {
              number:"d5",
              status:"occupied"
            }
            ]
          },
          {
            start_time:"9:00 PM",
            end_time:"12:30 AM",
            seats:[
              {
                number:"a1",
                status:"occupied"
              },
              {
                number:"a2",
                status:"occupied"
              },
              {
                number:"a3",
                status:"occupied"
              },
              {
                number:"a4",
                status:"occupied"
              },
              {
                number:"a5",
                status:"occupied"
              },
              {
                number:"b1",
                status:"vacant"
              },
              {
                number:"b2",
                status:"vacant"
              },
              {
                number:"b3",
                status:"vacant"
              },
              {
                number:"b4",
                status:"vacant"
              },
              {
                number:"b5",
                status:"vacant"
              },
              {
                number:"c1",
                status:"vacant"
              },
              {
                number:"c2",
                status:"vacant"
              },
              {
                number:"c3",
                status:"vacant"
              },
              {
                number:"c4",
                status:"vacant"
              },
              {
                number:"c5",
                status:"vacant"
              },
              {
                number:"d1",
                status:"vacant"
              },
              {
                number:"d2",
                status:"vacant"
              },
              {
                number:"d3",
                status:"vacant"
              },
              {
                number:"d4",
                status:"vacant"
              },
              {
                number:"d5",
                status:"vacant"
              }
              ]
          }
        ]
       },
       {
        name:"AGS Cinema",
        address:"Vivira Mall",
        shows:[
          {
            start_time:"10:00 AM",
            end_time:"12:30 PM",
            seats:[
              {
                number:"a1",
                status:"occupied"
              },
              {
                number:"a2",
                status:"occupied"
              },
              {
                number:"a3",
                status:"occupied"
              },
              {
                number:"a4",
                status:"occupied"
              },
              {
                number:"a5",
                status:"occupied"
              },
              {
                number:"b1",
                status:"vacant"
              },
              {
                number:"b2",
                status:"vacant"
              },
              {
                number:"b3",
                status:"vacant"
              },
              {
                number:"b4",
                status:"vacant"
              },
              {
                number:"b5",
                status:"vacant"
              },
              {
                number:"c1",
                status:"vacant"
              },
              {
                number:"c2",
                status:"vacant"
              },
              {
                number:"c3",
                status:"vacant"
              },
              {
                number:"c4",
                status:"vacant"
              },
              {
                number:"c5",
                status:"vacant"
              },
              {
                number:"d1",
                status:"vacant"
              },
              {
                number:"d2",
                status:"vacant"
              },
              {
                number:"d3",
                status:"vacant"
              },
              {
                number:"d4",
                status:"vacant"
              },
              {
                number:"d5",
                status:"vacant"
              }
              ]
          },
          {
            start_time:"9:00 PM",
            end_time:"12:30 AM",
            seats:[
              {
                number:"a1",
                status:"occupied"
              },
              {
                number:"a2",
                status:"occupied"
              },
              {
                number:"a3",
                status:"occupied"
              },
              {
                number:"a4",
                status:"occupied"
              },
              {
                number:"a5",
                status:"occupied"
              },
              {
                number:"b1",
                status:"vacant"
              },
              {
                number:"b2",
                status:"vacant"
              },
              {
                number:"b3",
                status:"vacant"
              },
              {
                number:"b4",
                status:"vacant"
              },
              {
                number:"b5",
                status:"vacant"
              },
              {
                number:"c1",
                status:"vacant"
              },
              {
                number:"c2",
                status:"vacant"
              },
              {
                number:"c3",
                status:"vacant"
              },
              {
                number:"c4",
                status:"vacant"
              },
              {
                number:"c5",
                status:"vacant"
              },
              {
                number:"d1",
                status:"vacant"
              },
              {
                number:"d2",
                status:"vacant"
              },
              {
                number:"d3",
                status:"vacant"
              },
              {
                number:"d4",
                status:"vacant"
              },
              {
                number:"d5",
                status:"vacant"
              }
              ]
          }
        ]
       }
     ]
   }
   
   movie1={
    imageUrl:"../../assets/darbar.jpg",
    name:"Darbar",
    theaters:[
      {
       name:"PVR Cinema",
       address:"Marina Mall",
       shows:[
         {
           start_time:"1:00 PM",
           end_time:"3:00 PM",
           seats:[
            {
              number:"a1",
              status:"vacant"
            },
            {
              number:"a2",
              status:"vacant"
            },
            {
              number:"a3",
              status:"vacant"
            },
            {
              number:"a4",
              status:"vacant"
            },
            {
              number:"a5",
              status:"vacant"
            },
            {
              number:"b1",
              status:"vacant"
            },
            {
              number:"b2",
              status:"vacant"
            },
            {
              number:"b3",
              status:"vacant"
            },
            {
              number:"b4",
              status:"vacant"
            },
            {
              number:"b5",
              status:"vacant"
            },
            {
              number:"c1",
              status:"vacant"
            },
            {
              number:"c2",
              status:"vacant"
            },
            {
              number:"c3",
              status:"vacant"
            },
            {
              number:"c4",
              status:"vacant"
            },
            {
              number:"c5",
              status:"vacant"
            },
            {
              number:"d1",
              status:"vacant"
            },
            {
              number:"d2",
              status:"vacant"
            },
            {
              number:"d3",
              status:"vacant"
            },
            {
              number:"d4",
              status:"vacant"
            },
            {
              number:"d5",
              status:"vacant"
            }
            ]
         },
         {
           start_time:"9:00 PM",
           end_time:"12:30 AM",
           seats:[
            {
              number:"a1",
              status:"vacant"
            },
            {
              number:"a2",
              status:"vacant"
            },
            {
              number:"a3",
              status:"vacant"
            },
            {
              number:"a4",
              status:"vacant"
            },
            {
              number:"a5",
              status:"vacant"
            },
            {
              number:"b1",
              status:"vacant"
            },
            {
              number:"b2",
              status:"vacant"
            },
            {
              number:"b3",
              status:"vacant"
            },
            {
              number:"b4",
              status:"vacant"
            },
            {
              number:"b5",
              status:"vacant"
            },
            {
              number:"c1",
              status:"vacant"
            },
            {
              number:"c2",
              status:"vacant"
            },
            {
              number:"c3",
              status:"vacant"
            },
            {
              number:"c4",
              status:"vacant"
            },
            {
              number:"c5",
              status:"vacant"
            },
            {
              number:"d1",
              status:"vacant"
            },
            {
              number:"d2",
              status:"vacant"
            },
            {
              number:"d3",
              status:"vacant"
            },
            {
              number:"d4",
              status:"vacant"
            },
            {
              number:"d5",
              status:"vacant"
            }
            ]
         }
       ]
      },
      {
       name:"AGS Cinema",
       address:"Vivira Mall",
       shows:[
         {
           start_time:"7:30 AM",
           end_time:"10:00 AM",
           seats:[
            {
              number:"a1",
              status:"vacant"
            },
            {
              number:"a2",
              status:"vacant"
            },
            {
              number:"a3",
              status:"vacant"
            },
            {
              number:"a4",
              status:"vacant"
            },
            {
              number:"a5",
              status:"vacant"
            },
            {
              number:"b1",
              status:"vacant"
            },
            {
              number:"b2",
              status:"vacant"
            },
            {
              number:"b3",
              status:"vacant"
            },
            {
              number:"b4",
              status:"vacant"
            },
            {
              number:"b5",
              status:"vacant"
            },
            {
              number:"c1",
              status:"vacant"
            },
            {
              number:"c2",
              status:"vacant"
            },
            {
              number:"c3",
              status:"vacant"
            },
            {
              number:"c4",
              status:"vacant"
            },
            {
              number:"c5",
              status:"vacant"
            },
            {
              number:"d1",
              status:"vacant"
            },
            {
              number:"d2",
              status:"vacant"
            },
            {
              number:"d3",
              status:"vacant"
            },
            {
              number:"d4",
              status:"vacant"
            },
            {
              number:"d5",
              status:"vacant"
            }
            ]
         },
         {
           start_time:"6:00 PM",
           end_time:"8:30 PM",
           seats:[
            {
              number:"a1",
              status:"vacant"
            },
            {
              number:"a2",
              status:"vacant"
            },
            {
              number:"a3",
              status:"vacant"
            },
            {
              number:"a4",
              status:"vacant"
            },
            {
              number:"a5",
              status:"vacant"
            },
            {
              number:"b1",
              status:"vacant"
            },
            {
              number:"b2",
              status:"vacant"
            },
            {
              number:"b3",
              status:"vacant"
            },
            {
              number:"b4",
              status:"vacant"
            },
            {
              number:"b5",
              status:"vacant"
            },
            {
              number:"c1",
              status:"vacant"
            },
            {
              number:"c2",
              status:"vacant"
            },
            {
              number:"c3",
              status:"vacant"
            },
            {
              number:"c4",
              status:"vacant"
            },
            {
              number:"c5",
              status:"vacant"
            },
            {
              number:"d1",
              status:"vacant"
            },
            {
              number:"d2",
              status:"vacant"
            },
            {
              number:"d3",
              status:"vacant"
            },
            {
              number:"d4",
              status:"vacant"
            },
            {
              number:"d5",
              status:"vacant"
            }
            ]
         }
       ]
      }
    ]
  }
  

  ngOnInit() {
    this.user=environment.user;
    this.getMovies();

    // this.userService.loggedInUser.subscribe(user => {
    //   this.user = user;
    //   if (!this.user) {
    //       this.logout()
    //   }
    // });
  }


  addMovie(){
    this.movieService.addMovie(environment.url,this.movie2).subscribe(data => {
      console.log(data);
    })

  }

  getMovies(){
    this.movieService.getMovies(environment.url).subscribe(data => {
      console.log(data);
      this.movies_list=data;
    })
}

deleteMovies(){
  this.movieService.deleteMovie(environment.url,"Darbar").subscribe(data => {
    console.log(data);
    this.movies_list=data;
  })
  this.movieService.deleteMovie(environment.url,"Geetha Govindam").subscribe(data => {
    console.log(data);
    this.movies_list=data;
  })
}

logout(){
      this.router.navigateByUrl('/loginPage');
      environment.user="";
      // this.userService.changeLoggedInUser(null);
}
}
